spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 8588f14ade469896694c1061ceace0da
            client-secret: OnUroitWJ47M5DnsJE6wRZJEKuII5vIu
            redirect-uri: "http://13.209.179.25:8081/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    url: jdbc:mysql://yoondb.cnwom4kocpo9.ap-northeast-2.rds.amazonaws.com:3306/yoondb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 # ?? ?????? DB ??
    username: admin   # ?? ??? ??
    password: sin020511   # ?? ??? ??
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # ???? create -> ???? update
    show-sql: true

server:
  port: 8081  # ?????? ??? 8081? ??

