spring:
  datasource:
    url: jdbc:mysql://yoondb.cnwom4kocpo9.ap-northeast-2.rds.amazonaws.com:3306/yoondb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 # ?? ?????? DB ??
    username: admin   # ?? ??? ??
    password: sin020511   # ?? ??? ??
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # ???? create -> ???? update
    show-sql: true

server:
  port: 8081  # ?????? ??? 8081? ??
